name: simplenotes
description: "Flutter project with notes."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-273.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  logger: ^2.3.0
  go_router: ^14.2.0
  flutter_lints: ^4.0.0
  dio: ^5.4.3+1
  device_info_plus: ^9.1.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true